
# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Set your personal hyprland configuration here

input {
    kb_layout=us
    kb_variant=altgr-intl
    }

# Add workspaces rules
workspace = 1, monitor:DP-1
